/* eslint-disable react/no-children-prop */
export { CCGCarousel } from './comps/carousel'
export { Contact } from './bodies/contact'
export { Dropdown } from './comps/dropdown'
export { Svg, Icons } from './comps/icons'
export { Container, Header, Footer, Title, Menu } from './comps/layout'
export { Nav, NavMobile } from './comps/nav'
export { SolutionsList } from './comps/solutionslist'
export { Tabs } from './comps/tabs'
export { Testimonies } from './comps/testimonies'
export { Timeline } from './comps/timeline'
